### ISSUE TITLE
Create a component

### ISSUE THREAD

**Issue by camelPhonso** [camelPhonso/mockup#1]
The tests on our app are expecting to find a dropdown component on the page!

You need to create a component that renders a dropdown component and make sure it's displayed when the app runs.

I have set up the structure of the app with a folder specifically for components - so you should create your component in that folder.

**Comment by mb556** [comment]
Component acts separately, so you can change one section of the app without needing to update everything.
Components come in two types, Class components and Function components.

**Comment by mb556** [comment]
can i be assigned to the task please

**Comment by camelPhonso** [comment]
> can i be assigned to the task please

it's yours Mohamed.

Please remember the guidance I left in the README about tagging this issue in your commit messages. Can you leave here a short message describing your plan of action for this issue (just let me know how you are planning to design the component and what you expect to have in your pr)

**Comment by mb556** [comment]
first error 
sh: react-scripts: command not found
