### ISSUE TITLE
Make the component display all Routes

### ISSUE THREAD

**Issue by camelPhonso** [camelPhonso/mockup#4]
For this mock we won't fetch the data, instead I've given you a file called `getAllRoutes.js` that exports all routes.

You need to make sure that this information is displayed by your component.

**whatch out** - we don't want the component to render this information by default.

In order to properly make use of React you should make sure the component gets this data from the page where it's being rendered and updates it's display accordingly.

**Comment by PL1106** [comment]
!request

**Comment by camelPhonso** [comment]
This issue is assigned to you, but keep in mind this is likely to overlap with mohamed's issue which will give you the component. Make sure you plan this accordingly
